services:
  # --- Serviço do Front-end ---
  frontend:
    build: ./front
    container_name: meu-projeto-frontend
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - minha-rede

  # --- Serviço do Back-end (API Spring Boot) ---
  api:
    build: ./back
    container_name: springboot-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis  # MODIFICADO: Adicionada dependência do Redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/codeconnect?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis       # ADICIONADO: Host do Redis
      SPRING_DATA_REDIS_PORT: 6379        # ADICIONADO: Porta do Redis
    networks:
      - minha-rede

  # --- Serviço do Banco de Dados ---
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: codeconnect
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha-rede

  # --- Serviço do Redis (Caching) --- # ADICIONADO: Novo serviço Redis
  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - minha-rede

volumes:
  mysql_data:

networks:
  minha-rede: